name: CoinBox CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Installer les dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Exécuter les tests avec couverture
      - name: Run tests and generate coverage report
        run: |
          pip install coverage
          coverage run -m unittest discover
          coverage html

      # Sauvegarder le rapport de couverture HTML comme artefact
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov
